"""Modernized sqlalchemy implementation

Revision ID: a2b4b176089f
Revises: b085abab72bc
Create Date: 2026-01-12 02:02:45.677572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b4b176089f'
down_revision: Union[str, None] = 'b085abab72bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('max_nominations',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_short',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_note',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('grouping',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('nominations', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('movie_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('grouping',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('has_note',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_short',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('max_nominations',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
