"""Added key-date table

Revision ID: ae2999b59058
Revises: a2b4b176089f
Create Date: 2026-01-22 07:34:14.086400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2999b59058'
down_revision: Union[str, None] = 'a2b4b176089f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_dates',
    sa.Column('key_date_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key_date_id')
    )
    with op.batch_alter_table('key_dates', schema=None) as batch_op:
        batch_op.create_index('idx_key_dates_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_dates', schema=None) as batch_op:
        batch_op.drop_index('idx_key_dates_timestamp')

    op.drop_table('key_dates')
    # ### end Alembic commands ###
