"""initial migration

Revision ID: b085abab72bc
Revises: 
Create Date: 2025-01-31 02:55:58.690842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import backend.data.db_schema

# revision identifiers, used by Alembic.
revision: str = 'b085abab72bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', backend.data.db_schema.CategoryID_SQL(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('max_nominations', sa.Integer(), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('has_note', sa.Boolean(), nullable=False),
    sa.Column('grouping', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('movies',
    sa.Column('movie_id', backend.data.db_schema.MovieID_SQL(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('movie_db_id', sa.String(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('subtitle_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index('idx_movies_year', 'movies', ['year'], unique=False)
    op.create_table('users',
    sa.Column('user_id', backend.data.db_schema.UserID_SQL(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('letterboxd', sa.String(), nullable=True),
    sa.Column('email', backend.data.db_schema.Email_SQL(), nullable=True),
    sa.Column('last_letterboxd_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('nominations',
    sa.Column('nomination_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('movie_id', backend.data.db_schema.MovieID_SQL(), nullable=True),
    sa.Column('category_id', backend.data.db_schema.CategoryID_SQL(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('nomination_id')
    )
    op.create_index('idx_nominations_year', 'nominations', ['year'], unique=False)
    op.create_table('watchlist',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('user_id', backend.data.db_schema.UserID_SQL(), nullable=False),
    sa.Column('movie_id', backend.data.db_schema.MovieID_SQL(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.create_index('idx_watchlist_user', 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_user', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('idx_nominations_year', table_name='nominations')
    op.drop_table('nominations')
    op.drop_table('users')
    op.drop_index('idx_movies_year', table_name='movies')
    op.drop_table('movies')
    op.drop_table('categories')
    # ### end Alembic commands ###
